version: '3'

services:
  caddy:
    image: caddy:latest
    ports:
      - "80:80"     # HTTP
      - "443:443"   # HTTPS
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile  # Configuratie
      - ./website:/srv                       # Website-bestanden
    depends_on:
      - php
      - db

  php:
    image: php:8.2-fpm
    volumes:
      - ./website:/srv

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: wachtwoord123
      MYSQL_DATABASE: sensordata
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - "8080:80"
   # environment:
    #  PMA_HOST: db
     # PMA_USER: root
      #PMA_PASSWORD: wachtwoord123

volumes:
  db_data:
